#!/usr/bin/env python
# -*- coding: utf-8 -*-

ROSSEL_SAME_OWNER = [
    'passionsante.be',
    'references.be',
    'enmemoire.sudinfo.be',
    'vlan.be',
    'gezondheid.be',
    'soirmag.be',
    'passiondesmontres.lesoir.be',
    'oeuvres.lesoir.be',
    'groupolitan.be',
    'rosseladvertising.be',
    'jobscareer.be',
    'jobsregions.be',
    'standard.sudpresse.be',
    'starnews.sudpresse.be',
    'enmemoire.be',
    '7dimanche.be',
    'sillonbelge.be',
    'netevents.be',
    'ticketnet.be',
    'cinenews.be',
    'rendez-vous.be',
    'nightcode.be',
    'lecho.be',
    'belegger.tijd.be',
    'tijd.be',
    'sabato.lecho.be',
    'monargent.lecho.be',
    'investisseur.be',
    'rtl.be',
    'belrtl.be',
    'rtlinfo.be',
    'radiocontact.be',
    'clubrtl.be',
    'plugtv.be',
    'rtlsport.be',
    'lavoixdunord.fr',
    'lavoixauto.com',
    'courrier-picard.fr',
    'lejournaldesflandres.fr',
    'lasemainedansleboulonais.fr',
    'meura.net',
    'lavoixdessports.com',
    'lavoixannonces.com',
    'nordlittoral.fr',
    'lepharedunkerquois.fr',
    'nordwaymagazine.com',
    'memoire.lavoixdunord.fr',
    'lavoiximmo.com',
    'lavoixletudiant.fr',
    'lesechosdutouquet.fr',
    'lavenirdelartois.fr',
    'nordstages.com',
    'mycontact.fr',
    'lavoixpourlesfemmes.fr',
    'lavoixeco.com',
    'directlille.com',
    'lereveildeberck.fr',
    'weo.fr',
    'neptv.com',
    'lavoixemploi.com',
    'nordeclair.fr',
    'lechodelalys.fr',
    'journaldemontreuil.fr'
]

LESOIR_SAME_OWNER = []
LESOIR_SAME_OWNER.extend(ROSSEL_SAME_OWNER)
LESOIR_SAME_OWNER.append("sudinfo.be")
SUDINFO_SAME_OWNER = []
SUDINFO_SAME_OWNER.extend(ROSSEL_SAME_OWNER)
SUDINFO_SAME_OWNER.append("lesoir.be")
